TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
# ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Optimization of db files using dbst (DEFAULT: NO)
# DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

# db templates
#DB += pgpCamlinkBase.template
DB += AxiVersion.db
DB += w8-aliases.db
DB += Ads42Lbx9.db
DB += BatcherEventBuilder.db
DB += roguePcie.db
DB += TimingRx.template
DB += TriggerEventManager.template
DB += putMonitor.template
DB += rbvMonitor.template
DB += PgpStrmMon.db
DB += PgpCannedSequences.db
DB += PgpChCannedSequences.db
DB += wave8Data.db
DB += wave8Reg.db

# Install archive files
#ARCHIVE += foo.tpl-arch

# Install autosave files
#REQ     += foo.req

# Install tpl-cfg files
CFG += defaults_LCLS-I.tpl-cfg

#----------------------------------------------------

include $(TOP)/configure/RULES
#----------------------------------------
# ADD RULES AFTER THIS LINE

